### ISSUE TITLE
Moving to coq-community ?

### ISSUE THREAD

**Issue by spitters** [HoTT/HoTT#947]
Shall we move to the coq-community and remain the maintainers?

https://github.com/coq-community/manifesto/

I think it will increase visibility and facilitate maintainance of tools, like the issues we had with the graphs.

**Comment by spitters** [comment]
@JasonGross The new nix-based CI my make things easier for us:
https://github.com/coq-community/qarith-stern-brocot/pull/2

**Comment by mikeshulman** [comment]
What would this mean concretely?

**Comment by spitters** [comment]
coq-community is a community supported variant of the coq-contribs.
We would transfer ownership (settings-> transfer ownership) to the coq-community github organization.

Is that what you mean?

**Comment by mikeshulman** [comment]
I mean, how would it affect our daily activities?  Would we continue doing everything the same way?  What does "ownership" mean in practice?

**Comment by spitters** [comment]
We would still be maintaining it, and I don't see a reason to change the way we are working.
However, silly things like travis stopping to work because of dpdgraph would be more easily spotted by others and I hope be fixed faster, because it would likely effect more projects.

I've already moved
https://github.com/coq-community/math-classes
and
https://github.com/c-corn/corn

To the coq-community and got a bug report about case-insensitive file systems (Windows) which was then fixed with the help of the community.

@Zimmi48 could you help us to decide whether it makes sense it include HoTT in the coq-community.

**Comment by spitters** [comment]
Ownership would mean that administrators of the coq-community could delete the project, for instance.
I think they are benevolent, but it's something to consider. @Zimmi48 ?

**Comment by mikeshulman** [comment]
Even if they suddenly became malevolent, we would still have all our forks and be able to re-create the project elsewhere, right?

**Comment by spitters** [comment]
Right

from my phone

**Comment by Zimmi48** [comment]
Hi all,
@spitters Your enthusiasm for coq-community is very appreciated.

> I think it will increase visibility and facilitate maintainance of tools, like the issues we had with the graphs.

I somehow doubt that this would really increase visibility; I would rather say that it would increase visibility to some people and decrease it to some others: I think lots of people land on https://github.com/HoTT through https://github.com/HoTT/book. Then, they find https://github.com/HoTT/HoTT which seems like the most important repository because it is called the same as the organization itself. If this repository was moved to https://github.com/coq-community, these people might very well think that there is only an Agda formalization.

Regarding the sharing of the tools and good practices, my goal is to use coq-community as a playground to experiment with them, but everything that turns out to be sufficiently useful and of general purpose will be shared of course, and can easily be replicated outside of coq-community. It will be important to have good documentation so that this is easy.

Given how new coq-community, I suggest to not rush and see how things work out in practice, and reconsider this option in a few months.

**Comment by mikeshulman** [comment]
Good point about visibility.  (Though it has always seemed a trifle unfair that we took the name HoTT/HoTT instead of HoTT/HoTT-Coq and relegated the Agda folks to HoTT/HoTT-Agda.)

**Comment by Alizter** [comment]
Shall we close this issue?
